# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FpUU-SCk8BgVKZ7HCJECOe5jX79cC-38
"""

import tweepy
from textblob import TextBlob

consumer_key = 'kNUlFVnkKaDHL2LmbFCcL3vB9'
consumer_secret = 'IRoCoL6qDxio3iirC63sPwswkh20cJXpzBCzsAJ3anzvUbkAHL'
access_token = '1492044764799115266-IYcwOMQ6Yd6TCuKSqwh0nfJyfTUtoS'
access_token_secret = '4scpXoux5uPhZwS6jlEt3kCb2ORtUB1Was13htrSCy7vy'


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
                        # set access token and secret
auth.set_access_token(access_token, access_token_secret)
                        # create tweepy API object to fetch tweets
api = tweepy.API(auth)

public_tweets=api.search(q="covid usa",lang="en")

for tweet in public_tweets:
  print(tweet.text)
  
  analysis=TextBlob(tweet.text)
  print(analysis.sentiment)
  if analysis.sentiment[0]>0:
    print('Positive')
    print()
  elif analysis.sentiment[0]<0:
    print('negative')
    print()
  else:
    print('neutral')
    print()

